# 你的网站名
site_name: Android-Vast-Extension

site_url: https://github.com/Android-Vast-Extension/Website/

repo_name: Android-Vast-Extension
repo_url: https://github.com/SakurajimaMaii/Android-Vast-Extension

edit_uri: blob/main/docs/

# 主题设置
theme:
  name: material
  language: zh
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: 暗色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: 亮色模式
  features:
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=nav#navigation-tabs
    - navigation.tabs
    - navigation.tabs.sticky
    # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/?h=edit#code-actions
    - content.action.edit
    - content.tabs.link

# 版权
copyright: This website follows MIT

# 插件
plugins:
  - i18n:
      default_language: zh
      material_alternate: true
      languages:
        zh:
          name: 简体中文
          build: true
        en:
          name: English
          build: true
      nav_translations:
        zh:
          App data and files : 应用数据与文件
          App entry points : 应用入口点
          App resources : 应用资源
          Architecture components : 架构组件
          Connectivity : 连接性
          Core topics : 核心主题
          Debug : 调试
          Documents : 文档
          Extension : 拓展
          Images : 图像
          Information get : 信息获取
          Init : 初始化
          Lifecycle aware components : 生命周期感知型组件
          Performing network operations : 执行网络操作
          Ui : 界面
          Ui layer libraries : 界面层库
          View bind : 视图绑定
        en:
          前言 : Preface
          概览 : Introduction
          初始化 : Initialization
          日志 : Logcat
          广播 : Broadcast
          GPS状态 : GPS
          Class转换为Map : Class to Map
          常见Intent : Normal Intent
  - search:
      lang: ja
  - awesome-pages:
      strict: false

# LaTeX支持
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.tilde
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.highlight:
      use_pygments: true
  - footnotes
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
